# Generated by Django 5.1.7 on 2025-03-24 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=255, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущая сумма')),
                ('deadline', models.DateField(default='2025-12-31', verbose_name='Срок достижения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Последнее уведомление о прогрессе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
